namespace :db do
  desc 'Add admin account'
  task :create_admin, [:password] => [:environment] do |t, args|
    password = args.password
    if password.nil?
      password = Devise.friendly_token.first(8)
      puts "Autogenerated password is #{password}"
    end

    admin_workshop = Workshop.find_by(description: 'Admin')
    admin = User.create!(username: 'admin',
                         email: 'admin@',
                         password: password,
                         password_confirmation: password,
                         workshop: admin_workshop )
    admin.confirmed_at = DateTime.now
    admin.admin!
    admin.save
  end

  desc 'Create user'
  task :create_user, [:email, :password] => [:environment] do |t, args|
    password = args.password
    if password.nil?
      password = Devise.friendly_token.first(8)
      puts "Autogenerated password is #{password}"
    end
    address = Mail::Address.new args.email
    users = User.all().where(email: args.email)
    if users.blank?
      user = User.create!(username: address.local,
                          email: args.email,
                          password: password,
                          password_confirmation: password)
      user.confirmed_at = DateTime.now
    else
      user = users.first
      user.password = password
      user.password_confirmation = password
      user.confirmed_at = DateTime.now
    end
    user.save
  end
end