namespace :db do
  desc 'Add admin account'
  task :create_admin, [:password] => [:environment] do |t, args|
    password = args.password
    if password.nil?
      password = User.generate_password
      puts "Autogenerated password is #{password}"
    end

    admin = User.create!(username: 'ichornous',
                         email: 'igor@chornous.com',
                         password: password,
                         password_confirmation: password)
    admin.confirmed_at = DateTime.now
    admin.admin!
    admin.save
  end
end